---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: check-mk-config-local-storage
 namespace: check-mk
spec:
 accessModes:
  - ReadWriteOnce
 storageClassName: "local-storage"
 resources:
   requests:
     storage: 1Mi
 selector:
   matchLabels:
     type: local
     env: tt
 volumeName: "check-mk-config-local-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: check-mk-backup-local-storage
 namespace: check-mk
spec:
 accessModes:
  - ReadWriteOnce
 storageClassName: "local-storage"
 resources:
   requests:
     storage: 100Mi
 selector:
   matchLabels:
     type: local
     env: tt
 volumeName: "check-mk-backup-local-storage"
