apiVersion: v1
kind: Service
metadata:
  name: svc-check-mk-web
  namespace: check-mk
  labels:
    app: check-mk
spec:
  # uncomment the next and delete the following line if you want to use a NodePort
  #type: NodePort
  type: LoadBalancer
  ports:
  - port: 80
    name: web
    targetPort: 5000
  - port: 6556
    name: check-mk-agent
  - port: 6557
    name: check-mk-multisite
  selector:
    app: check-mk